# Specify a command to be executed
# like `/bin/bash -l`, `ls`, or any other commands
# the default is bash for Linux
# or powershell.exe for Windows
command: zsh

# Specify the current working directory path
# the default is the current working directory path
cwd: null

# Export additional ENV variables
env:
  recording: true

# Explicitly set the number of columns
# or use `auto` to take the current
# number of columns of your shell
cols: 70

# Explicitly set the number of rows
# or use `auto` to take the current
# number of rows of your shell
rows: 7

# Amount of times to repeat GIF
# If value is -1, play once
# If value is 0, loop indefinitely
# If value is a positive number, loop n times
repeat: 0

# Quality
# 1 - 100
quality: 100

# Delay between frames in ms
# If the value is `auto` use the actual recording delays
frameDelay: auto

# Maximum delay between frames in ms
# Ignored if the `frameDelay` isn't set to `auto`
# Set to `auto` to prevent limiting the max idle time
maxIdleTime: 1000

# The surrounding frame box
# The `type` can be null, window, floating, or solid`
# To hide the title use the value null
# Don't forget to add a backgroundColor style with a null as type
frameBox:
  type: solid
  title: null
  style:
    backgroundColor: "#282a36"
    border: 0px black solid
    boxShadow: none
    margin: 0px

# Add a watermark image to the rendered gif
# You need to specify an absolute path for
# the image on your machine or a URL, and you can also
# add your own CSS styles
watermark:
  imagePath: null
  style:
    position: absolute
    right: 15px
    bottom: 15px
    width: 100px
    opacity: 0.9

# Cursor style can be one of
# `block`, `underline`, or `bar`
cursorStyle: block

# Font family
# You can use any font that is installed on your machine
# in CSS-like syntax
fontFamily: "Monaco, Lucida Console, Ubuntu Mono, Monospace"

# The size of the font
fontSize: 12

# The height of lines
lineHeight: 1

# The spacing between letters
letterSpacing: 0

# Theme
theme:
  background: "transparent"
  foreground: "#eff0eb"
  cursor: "#c7c7c7"
  black: "#232628"
  red: "#ff5c57"
  green: "#5af78e"
  yellow: "#f3f99d"
  blue: "#57c7ff"
  magenta: "#ff6ac1"
  cyan: "#9aedfe"
  white: "#f1f1f0"
  brightBlack: "#686868"
  brightRed: "ff5c57"
  brightGreen: "#5af78e"
  brightYellow: "#f3f99d"
  brightBlue: "#57c7ff"
  brightMagenta: "#ff6ac1"
  brightCyan: "#9aedfe"
  brightWhite: "#eff0eb"
